### ISSUE TITLE
CRITICAL errors in eloipool.log

### ISSUE THREAD

**Issue by ShurikAg** [ZeroASIC/eloipool-server#6]
What does this mean and how to get read of it?

Thanks.

```
014-02-15 04:20:06,421  merkleMaker CRITICAL    Traceback (most recent call last):
  File "/opt/eloipool-server/eloipool/merklemaker.py", line 692, in run
    self.merkleMaker_I()
  File "/opt/eloipool-server/eloipool/merklemaker.py", line 682, in merkleMaker_I
    self.merkleMaker_II()
  File "/opt/eloipool-server/eloipool/merklemaker.py", line 648, in merkleMaker_II
    return self._updateMerkleTree()
  File "/opt/eloipool-server/eloipool/merklemaker.py", line 548, in _updateMerkleTree
    self._updateMerkleTree_I()
  File "/opt/eloipool-server/eloipool/merklemaker.py", line 512, in _updateMerkleTree_I
    r = self._updateMerkleTree_fromTS(TS)
  File "/opt/eloipool-server/eloipool/merklemaker.py", line 477, in _updateMerkleTree_fromTS
    MP = self._CallGBT(TS)
  File "/opt/eloipool-server/eloipool/merklemaker.py", line 327, in _CallGBT
    MP = access.getblocktemplate(self.GBTReq)
  File "/opt/eloipool-server/eloipool/bitcoinrpc/authproxy.py", line 116, in __call__
    raise JSONRPCException(response['error'])
bitcoinrpc.authproxy.JSONRPCException
```

**Comment by ShurikAg** [comment]
Just a note: Username and pass for rpc calls are matching...

**Comment by ZeroASIC** [comment]
I don't directly support eloipool.  Maybe you should check the documentation.  More so, as long as everything is working for your miner then you can ignore the warnings.

Make sure that you've given bitcoind enough time to sync to the network and then reboot the machine and try it again.
