### ISSUE TITLE
Eloipool displaying an error.

### ISSUE THREAD

**Issue by wakwo2** [ZeroASIC/eloipool-server#7]
Everything was set up properly and this is the error I am getting.

ERROR 1:

2014-02-19 16:43:02,707 StratumServer   ERROR   Traceback (most recent call last):
  File "/home/xxx/eloipool-server-master/eloipool/networkserver.py", line 392, in serve_forever
    f()
  File "/home/xxx/eloipool-server-master/eloipool/stratumserver.py", line 135, in sendJob
    self.push(self.server.JobBytes)
AttributeError: 'StratumServer' object has no attribute 'JobBytes'

I have seen more issues posted related to this error but you have not answered on how to fix it. 

ERROR 2:
2014-02-19 16:51:50,480 merkleMaker CRITICAL    Traceback (most recent call last):
  File "/home/xxx/eloipool-server-master/eloipool/merklemaker.py", line 692, in run
    self.merkleMaker_I()
  File "/home/xxx/eloipool-server-master/eloipool/merklemaker.py", line 682, in merkleMaker_I
    self.merkleMaker_II()
  File "/home/xxx/eloipool-server-master/eloipool/merklemaker.py", line 648, in merkleMaker_II
    return self._updateMerkleTree()
  File "/home/xxx/eloipool-server-master/eloipool/merklemaker.py", line 553, in _updateMerkleTree
    if self.needMerkle == 2:
AttributeError: 'merkleMaker' object has no attribute 'needMerkle'

**Comment by ZeroASIC** [comment]
I think several people have already solved this bug by making sure that bitcoind is in sync with the network and that eloipool is only running once.

Kill the extra eloipool instances that you may have started by accident and wait for bitcoind to finish syncing.  If that doesn't help make sure that you have the RPC password set correctly in all of your configs.  If all else fails just restart the machine completely and run the start script one time.

If that doesn't solve your problem then post another comment.

**Comment by wakwo2** [comment]
Running this command on my Ubuntu 12.04  

bfgminer -o stratum+tcp:/localhost:3334 -O MyAddress

I get the following error,

d a port, or have not set up workers
 [2014-02-21 00:33:33] Pool: 0  URL: stratum+tcp://localhost:3334  User: YourAdd
ress  Password:
 [2014-02-21 00:33:33] Press any key to exit, or BFGMiner will try again in 15s.

 [2014-02-21 00:33:49] No servers were found that could be used to get work from
.
 [2014-02-21 00:33:49] Please check the details from the list below of the serve
rs you have input
 [2014-02-21 00:33:49] Most likely you have input the wrong URL, forgotten to ad
d a port, or have not set up workers
 [2014-02-21 00:33:49] Pool: 0  URL: stratum+tcp://localhost:3334  User: YourAdd
ress  Password:
 [2014-02-21 00:33:49] Press any key to exit, or BFGMiner will try again in 15s.

My blockchain is up to date, I have confirmed that by running bitcoin-qt before bitcoind client, with a -datadir argument pointing at bitcoindata folder. 

I tried not using the ./startpool script, rather I executed the scripts individually, by ./run-bitcoind.sh first and then ./run-eloipool.sh
I waited till I get the first newblock notificatio script executed to start eloipool so that I give time to sync. 

I tried making a clean install of ubuntu (This is the 3rd one actually) I also tried to run it on a virtual box, and I still received the same error. 

I greatly appreciate your instant response. I am looking forward resolving this issue. Please let me know what other information you need.

**Comment by wakwo2** [comment]
I think I should also mention that, ERROR 1, appears only when I try to connect with bfgminer the way I demonstrated a comment above. 

ERROR 2: on the other hand appears the moment ./run-eloipool is executed and floods the command line.

**Comment by wakwo2** [comment]
Just out of a coincidence, Luke-Jr the developer of eloipool uploaded a fix for the bug related to this issue few minutes after this report. 

https://gitorious.org/bitcoin/eloipool/source/c62ac23f0d9ca2c2cf8dc8ce5dcfd925edc1f632:merklemaker.py

I greatly appreciate your support, ZeroAsic.

**Comment by ZeroASIC** [comment]
Just run the update script then.
